config/routes.rb
SimplePlan::Application.routes.draw do  

  devise_for :users, :controllers => { :registrations => "registrations" }
		
  match 'programs/grid_data', :to => 'programs#grid_data'
	match 'programs/list', :to => 'programs#list'
	match 'programs/filter', :to => 'programs#filter'
	
	resources :activities
	resources	:accounts	
	resources :services
	resources :profiles
	resources :partnerships
	resources	:categories
	resources	:products
  resources :program_categories
  resources :program_products
  resources :program_activities
	resources :imports
	resources :worksheets
	
	resources :budgets do
		resources :plans
	end
	
	resources	:plans do
		resources	:programs do
			member do
				get 'copy'
			end
		end
	end
	
	resources	:programs do
		member do
			get 'copy'
		end
		resources	:deals	
	end
	
	resources :deals do
		resources :deal_products
	end
		
	resources :deal_products do
		resources :deal_activities
	end
	
	namespace :user do
		root :to => 'users#dashboard'
	end
	
	match 'users' => 'users#dashboard', :as => 'user_root'

	match '/help',			:to => 'pages#help'
	match '/about',			:to => 'pages#about'
	match '/contact',		:to => 'pages#contact'
	match '/user',			:to => 'users#show'
	match '/users',			:to => 'users#index'
	
	root :to => 'pages#home'

  
end

app/models/program.rb
class Program < ActiveRecord::Base
	include ApplicationHelper
	
	belongs_to 	:seller, :class_name => "Account", :foreign_key => "seller_id"
	belongs_to 	:supplier, :class_name => "Account", :foreign_key => "supplier_id"	
	belongs_to	:account
	belongs_to	:plan
	belongs_to	:category
  
  has_many 		:deals
	has_many		:deal_products, :through => :deals
	has_many		:deal_activities, :through => :deal_products
	has_many  	:program_activities
	has_many  	:customers, :through => :deals, :class_name => "Account"
	
	 
	accepts_nested_attributes_for :deals
		
	def self.ttl_budget_cost(partners, account, plan)
		Program.sum('budget_rate * budget_volume', :conditions => [ "(account_id IN (?) OR account_id = (?)) AND plan_id = ?",
				partners, account, plan]) 
	end
	
	def self.plan_budget(plan)
		Plan.find(plan).budget_expense
	end
	
	def find_deals
		self.deals.all(:order => deals_order)
	end
	
	def find_assigned_categories
		self.categories.where()
	end
	
	def budget_cost
		if self.budget_rate && self.budget_volume
			self.budget_rate * self.budget_volume
		else
			0
		end
	end
	
	def plan_expense
		deals.sum("plan_rate * plan_volume")
	end
	
	def deals_order
		'id'
	end
	
	
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
include ApplicationHelper
before_filter { |c| c.set_zone "Application" }
before_filter	:validate_plan

  def index
		@title = "#{current_account.name} Programs"
		@program = @plan.programs.new
		@programs = @plan.programs.includes(:account, :category, :supplier, :seller)
		@categories = current_account.approved_categories.all
		@ttl_budget_cost = Program.ttl_budget_cost(current_partners, current_account, @plan)
		@plan_budget = Program.plan_budget(@plan)
		@service_needed = service_needed
		@suppliers = Account.find(:all, :conditions => {:service => 'supplier', :id => current_partners})
		@sellers = Account.find(:all, :conditions => {:service => 'seller', :id => current_partners})
	end
	
	def list
	end
	
	def show
		@program = Program.find(params[:id])
		@title = @program.name
	end

	def edit
		@program = Program.find(params[:id])
		@title = @program.name
	end
	
	def update
		@program = Program.find(params[:id])
		if @program.update_attributes(params[:program])
			flash[:success] = "Program updated."
			redirect_to programs_path
		else
			redirect_to programs_path
		end
	end
	
	def create
		@program = @plan.programs.build(params[:program])
		@program.account_id = current_account.id
		@program.plan_id = @plan.id
		if current_account.service == 'supplier'
			@program.supplier = current_account
		else
			@program.seller = current_account
		end
		
		if @program.save
			flash[:success] = "Successfully added a new program"
			redirect_to plan_programs_path
		else
			redirect_to plan_programs_path
		end
	end
	
	def destroy
    Program.find(params[:id]).destroy
    flash[:success] = "Program deleted."
    redirect_to programs_path
  end
	
	
	def validate_plan
		if !params[:plan_id]
			plan_id = current_user.profile.last_plan
		else
			plan_id = params[:plan_id]
		end
		@plan = Plan.find(plan_id)
		if current_account.partner_plans.include?(@plan)
			current_user.profile.set_last_plan(@plan.id)
		else
			flash[:error]='This plan is not available'
			redirect_to plans_path
		end
	end
	
	def service_needed
		current_account.service == 'supplier' ? 'seller' : 'supplier'
	end
	

	def grid_data
		page = (params[:page]).to_i
    rp = (params[:rp]).to_i
    query = params[:query]
    qtype = params[:qtype]
    sortname = params[:sortname]
    sortorder = params[:sortorder]
		
		case sortname
		when 'seller.name'
			sortname = 'accounts.name'
		when 'category.code'
			sortname = 'categories.code'
		end
				
		# Defaults		
		sortname ||= "program.id"
		sortorder ||= "asc"
		page ||= 1
		rp ||= 10
  
    start = ((page-1) * rp).to_i
		finish = start + rp - 1
    query = "%"+query+"%"

    # No search terms provided
    if(query == "%%")
			@programs = @plan.find_programs(sortname, sortorder)			
		else		
		 # User provided search terms
			@programs = @plan.search_programs(sortname, sortorder, query, qtype)
    end
		
		count = 0	
		return_data = Hash.new
		return_data[:page] = page
		collect_data = Array.new
				
		@programs.each do |program| 
			if program.deals.length > 0
				program.deals.each do |d|
					if (start..finish) === count
						collect_data << {:cell => [
							 '<a href=list?program_id='+d.program.id.to_s+'>'+d.program.id.to_s+'</a>',
							 d.program.seller.name,
							 d.program.code,
							 d.program.start_date ? d.program.start_date.strftime("%m/%d/%Y") : nil,
							 d.program.end_date ? d.program.end_date.strftime("%m/%d/%Y") : nil,
							 d.program.category.code,
							 d.customer_id,
							 d.status
						 ]}
					end
					count += 1			 
				end
			else
				if (start..finish) === count
					collect_data << {:cell => [
						'<a href=list?program_id='+program.id.to_s+'>'+program.id.to_s+'</a>',
						program.seller.name,
						program.code,
						program.start_date ? program.start_date.strftime("%m/%d/%Y") : nil,
						program.end_date ? program.end_date.strftime("%m/%d/%Y") : nil,
						program.category.code,
						nil,
						nil
					]}
				end
				count += 1
			end
		end
		return_data[:total] = count
		return_data[:rows] = collect_data
    # Convert the hash to a json object
    render :text=>return_data.to_json, :layout=>false
	end
	
end

app/views/programs/_new.html.erb



    <%= form_for([@plan, @program]) do |f| %>
      <div class="field">
        <td />
        <td><%= f.text_field :code, :class => "text_field", :value => @new != nil ? @new.code : nil %></td> 
        <td><%= f.text_field :name, :class => "text_field" %></td> 
        <td><%= f.text_field :descr, :class => "text_field" %></td>
        <td></td>
        <td><%= f.text_field :start_date, :class => "date_field" %></td>
        <td><%= f.text_field :end_date, :class => "date_field" %></td>
        <% if @service_needed == "supplier" %>
            <td><%= f.collection_select(:supplier_id, @suppliers, :id, :name, :prompt => "--select one--") %></td>
        <% else %>
            <td><%= f.collection_select(:seller_id, @sellers, :id, :name, :prompt => "--select one--") %></td>
        <% end %>
        <td><%= f.collection_select(:category_id, @categories, :id, :code, :prompt => "--select one--") %></td>            
      </div>
      <td><%= f.number_field :budget_rate, :step => 0.01, :class => "number_field" %></td>
      <td><%= f.number_field :budget_volume, :class => "number_field" %></td>
      <td>
      <div class="actions">
        <%= f.submit "Submit" %>
      </div>     
      </td>
      <td />
      <td />
      <td />
    <% end %>


app/views/programs/_program.erb
<tr>
  <td><%= program != nil ? program.seller.name : nil %></td>
  <td><%= program != nil ? link_to(program.code, program_deals_path(program.id)) : nil %></td>
  <td><%= program.start_date != nil ? program.start_date.to_s(:just_date) : nil%></td>
  <td><%= program.end_date != nil ? program.end_date.to_s(:just_date) : nil%></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>  
  <%= render program.deals %>  
</tr>

app/views/programs/_service.html.erb
<% if current_account.service != 'supplier' %>
  <%= program.supplier.name %>
<% else %>
  <%= program.seller != nil ? program.seller.name : nil %>
<% end %>	

app/views/programs/edit.html.erb
<h2>Edit Program</h2>

<%= form_for(@program) do |f| %>
  <div class="field">
    <%= f.label :name, "Code", :class => "field_label" %><br />
    <%= f.text_field :code %><br/>
  </div>
  <div class="field">
    <%= f.label :name, "Name", :class => "field_label" %><br />
    <%= f.text_field :name %><br/>
  </div>
  <div class="field">
    <%= f.label :name, "Descr", :class => "field_label" %><br />
    <%= f.text_field :descr %><br/>
  </div>

  <div class="field">
    <%= f.label :name, "Seller", :class => "field_label" %><br />
    <%= f.text_field :seller_id %><br/>
  </div>

  <div class="field">
    <%= f.label :name, "Start", :class => "field_label" %><br />
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :name, "End", :class => "field_label" %><br />
    <%= f.text_field :end_date %>
  </div>
  
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
  
  <p><%= link_to "Cancel", :back %></p>
  
<% end %>

app/views/programs/index.html.erb
<p class="trail"><%= link_to "Plans (#{@plan.code})", plans_path %> > Programs </p>
<h4>Total Program Plan: <%= currency_zero(@ttl_budget_cost) %> of <%= currency_zero(@plan_budget) %> Budget</h4>

<table id="projects-index" class="dataTable"> 
  <thead>
    <tr>
      <th />
      <th>Code</th>
      <th>Name</th>
      <th>Description</th>
      <th>Account</th>
      <th>Start</th>
      <th>End</th>
      <th><%= @service_needed.humanize %></th>
      <th>Category</th>
      <th>Budgeted Rate</th>
      <th>Budgeted Volume</th>
      <th>Budgeted Cost</th>
      <th>Planned Cost</th>
      <th />
      <th />
    </tr>
  </thead>
  <tbody>
    <% @programs.each do |p| %>
      <% if p.id %>
        <tr>
          <td><%= link_to "Deals", program_deals_path(p.id) %> </td>        
          <td><%= p.code %></td>
          <td><%= p.name %> </td>
          <td><%= p.descr %></td>
          <td><%= p.account.name %></td>
          <td><%= p.start_date && p.start_date.to_s(:just_date) %></td>
          <td><%= p.end_date && p.end_date.to_s(:just_date) %></td>
          <td><%= render :partial => "service", :locals => { :program => p } %>
          <td><%= p.category.code %></td>        
          <td class="number_field"><%= p.budget_rate && number_to_currency(p.budget_rate) %></td>
          <td class="number_field"><%= p.budget_volume && float_zero(p.budget_volume) %></td>
          <td class="number_field"><%= currency_zero(p.budget_cost) %></td>
          <td class="number_field"><%= currency_zero(p.plan_expense) %></td>
          <td><%= link_to "Edit", edit_plan_program_path(@plan, p) %></td>
          <td><%= link_to "Delete", p, :method => :delete, :confirm => "Please confirm deletion:",
                                                        :title => "Delete #{p.name}" %></td>
        </tr>
      <% end %>
    <% end %>
      
  </tbody>
</table>


<%= render :partial => 'new', :locals => { :program => @plan.programs.new, :new => @new_program } %>

      
<script>
  $(document).ready(function() {
    $('#projects-index').dataTable({
      "bJQueryUI": true
    });
  } );

</script>

app/views/programs/list.html.erb
<table id="flex1"></table>
<script type="text/javascript">
  $("#flex1").flexigrid
    (
    {
    method: 'GET',
    url: 'grid_data',
    dataType: 'json',
    colModel : [    
      {display: 'Id', name : 'programs.id', width : 30, sortable : true, align: 'left'},
      {display: 'Rep', name : 'seller.name', width : 100, sortable : true, align: 'left'},
      {display: 'Code', name : 'code', width : 100, sortable : true, align: 'left'},
      {display: 'Start', name : 'start_date', width : 75, sortable : true, align: 'left'},
      {display: 'End', name : 'end_date', width : 75, sortable : true, align: 'left'},
      {display: 'Category', name : 'category.code', width : 100, sortable : true, align: 'left'},
      {display: 'Customer', name : 'customer_id', width : 50, sortable : true, align: 'left'},
      {display: 'Status', name : 'status', width : 75, sortable : true, align: 'left'}
    ],
    searchitems : [
      {display: 'Id', name : 'programs.id'},
      {display: 'Code', name : 'programs.code'},
      {display: 'Rep', name : 'accounts.name'}
    ],
    sortname: "programs.id",
    sortorder: "asc",
    usepager: true,
    title: 'Programs',
    useRp: true,
    rp: 15,
    showTableToggleBtn: true,
    sizeable: true,
    width: 'auto',
    height: 'auto'
    }
  );
</script>

app/views/programs/show.html.erb
<%= render :partial => "shared/base_fields", :locals => { :object => @program } %>
	
  <div>
    <p><%= link_to "Edit", edit_program_path(@program) %></p>
    <p><%= link_to "Delete", @program, :method => :delete, :confirm => "Please confirm deletion:",
        :title => "Delete #{@program.name}" %></P>
    <p><%= link_to "Back", :back %></p>
  </div>																		

app/views/programs/test.html.erb
<h2><%=  @title %></h2>
<h4>Plan: <%= @plan.code %></h4>


<table id="worksheet">
  <% @plan.programs.each do |p| %>
    <tr>      
      <%= form_for p do |f| %>
        <td><%= f.object.seller != nil ? f.object.seller.name : nil %></td>        
        <td><%= f.object.code %></td>
        <td><%= f.text_field :start_date, :class => 'date_field', :value => (f.object.start_date.to_s(:just_date) unless f.object.start_date.nil?)%></td>
        <td><%= f.text_field :end_date, :class => 'date_field', :value => (f.object.start_date.to_s(:just_date) unless f.object.start_date.nil?)%></td>
      <% end %>
    </tr>
  <% end %>
  
        
</table>