config/routes.rb
SimplePlan::Application.routes.draw do  

  devise_for :users, :controllers => { :registrations => "registrations" }
		
  match 'programs/grid_data', :to => 'programs#grid_data'
	match 'programs/list', :to => 'programs#list'
	match 'programs/filter', :to => 'programs#filter'
	
	resources :activities
	resources	:accounts	
	resources :services
	resources :profiles
	resources :partnerships
	resources	:categories
	resources	:products
  resources :program_categories
  resources :program_products
  resources :program_activities
	resources :imports
	resources :worksheets
	
	resources :budgets do
		resources :plans
	end
	
	resources	:plans do
		resources	:programs do
			member do
				get 'copy'
			end
		end
	end
	
	resources	:programs do
		member do
			get 'copy'
		end
		resources	:deals	
	end
	
	resources :deals do
		resources :deal_products
	end
		
	resources :deal_products do
		resources :deal_activities
	end
	
	namespace :user do
		root :to => 'users#dashboard'
	end
	
	match 'users' => 'users#dashboard', :as => 'user_root'

	match '/help',			:to => 'pages#help'
	match '/about',			:to => 'pages#about'
	match '/contact',		:to => 'pages#contact'
	match '/user',			:to => 'users#show'
	match '/users',			:to => 'users#index'
	
	root :to => 'pages#home'

  
end

app/models/deal_product.rb
class DealProduct < ActiveRecord::Base
	belongs_to	:deal
  belongs_to  :product
	has_many		:deal_activities
	
	accepts_nested_attributes_for	:deal_activities
	
	def find_deal_activities
		self.deal_activities.joins(:activity).all(:order => deal_activities_order)
	end
	
	def deal_activities_order
		'activities.code'
	end
	
end

app/controllers/deal_products_controller.rb
class DealProductsController < ApplicationController
include ApplicationHelper
before_filter :find_deal
before_filter	:find_program
before_filter	:find_customer
before_filter :find_deal_products
before_filter	:find_products

  def create
		@deal_product = @deal.deal_products.build(params[:deal_product])
		if @deal_product.save
			flash[:success] = "Successfully added deal product"
			redirect_to deal_deal_products_path
		else
			flash[:error] = "Could not add new product"
			redirect_to programs_path
		end
	end
	
	def index
		@title = "Deal Products"
		@zone = "Application"
  end
	
	def edit
		@zone = "Application"
		@title = @deals.product.name
  end
	
  def show
		@zone = "Application"
		@deal = Deal.find(params[:deal_id])
		@title = @deal.code
  end
	
	def find_deal
		@deal = Deal.find(params[:deal_id])
	end
	
	def find_program
		@program = @deal.program
	end
	
	def find_customer
		@customer = Account.find(:first, :conditions => ["id = ?", @deal.customer_id])
		logger.debug "The object is #{@customer}"
	end
  
  def find_deal_products
    @deal_products = @deal.deal_products
  end
	
	def find_products
		@products = Product.find(:all, :conditions => ["id NOT IN (SELECT product_id FROM deal_products WHERE deal_id = ?)
				AND (account_id IN (?) OR account_id = ?)", @deal.id, current_partners, current_account])
	end
	
end

app/views/deal_products/_deal_product.html.erb
<tr>
    <td><%= deal_product != nil ? deal_product.deal.program.seller.name : nil %></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= deal_product != nil ? deal_product.product.code : nil %></td>
    <td></td>
    <%= render deal_product.deal_activities %>
  </tr>

app/views/deal_products/_new.html.erb
<%= form_for [@deal, deal_product] do |f|  %>
  <div class="field">
    <td><%= f.collection_select(:product_id, @products, :id, :code) %></td>
    <td><%= f.number_field :rate, :step => 0.01, :class => "number_field" %></td>
    <td><%= f.number_field :volume, :step => 1, :class => "number_field" %></td>
    <td><%= f.text_field :start_date, :class => "date_field" %></td>
    <td><%= f.text_field :end_date, :class => "date_field" %></td>
  
  
  </div>
  <div class="actions">
    <td>
      <%= f.submit "Submit" %>
    </td>
  </div>

<% end %>

app/views/deal_products/index.html.erb
<h4><%= link_to @deal.program.code, programs_path %> (<%= @deal.program.name %>)
  >> <%= link_to @customer.name, program_deals_path(@program) %></h4>
<h4>Products</h4>
<table>
  <tr>
    <th>Product</th>
    <th>Budgeted<br />Rate</th>
    <th>Volume</th>
    <th>Start</th>
    <th>End</th>
  </tr>
  
  <% @deal_products.each do |product| %>
    <tr>
      <%#TODO: Move path below to "Activities" Link%>
      <td><%= link_to product.product.code, deal_product_deal_activities_path(product) %></td>
      <td><%= product.rate %></td>
      <td><%= product.volume %></td>
      <td><%= product.start_date %></td>
      <td><%= product.end_date %></td>
    </tr>
  <% end %>  
    
  <tr>
    <%= render :partial => 'new', :locals => { :deal_product => @deal.deal_products.new } %>
  </tr>
  
</table>