config/routes.rb
SimplePlan::Application.routes.draw do  

  devise_for :users, :controllers => { :registrations => "registrations" }
		
  match 'programs/grid_data', :to => 'programs#grid_data'
	match 'programs/list', :to => 'programs#list'
	match 'programs/filter', :to => 'programs#filter'
	
	resources :activities
	resources	:accounts	
	resources :services
	resources :profiles
	resources :partnerships
	resources	:categories
	resources	:products
  resources :program_categories
  resources :program_products
  resources :program_activities
	resources :imports
	resources :worksheets
	
	resources :budgets do
		resources :plans
	end
	
	resources	:plans do
		resources	:programs do
			member do
				get 'copy'
			end
		end
	end
	
	resources	:programs do
		member do
			get 'copy'
		end
		resources	:deals	
	end
	
	resources :deals do
		resources :deal_products
	end
		
	resources :deal_products do
		resources :deal_activities
	end
	
	namespace :user do
		root :to => 'users#dashboard'
	end
	
	match 'users' => 'users#dashboard', :as => 'user_root'

	match '/help',			:to => 'pages#help'
	match '/about',			:to => 'pages#about'
	match '/contact',		:to => 'pages#contact'
	match '/user',			:to => 'users#show'
	match '/users',			:to => 'users#index'
	
	root :to => 'pages#home'

  
end

app/models/deal.rb
class Deal < ActiveRecord::Base
	belongs_to 	:program
	belongs_to 	:customer, :class_name => "Account"
	has_many		:deal_products
	has_many		:deal_categories, :through => :deal_products
	
	accepts_nested_attributes_for	:deal_products
	
	#TODO:	Make customer unique
	
	DEAL_STATUS = %w[planned offered accepted rejected canceled]
	
	def find_deal_products
		self.deal_products.joins(:product).all(:order => deal_product_order)
	end
	
	def deal_product_order
		'products.code ASC'
	end
	
	def plan_expense
		(self.plan_rate ||= 0) * (self.plan_volume ||= 0)
	end
	
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
include ApplicationHelper
before_filter	:find_program
before_filter :find_deals
before_filter	:find_customers
before_filter :find_plan

  def create
		@deal = @program.deals.build(params[:deal])
		@deal.owner_id = current_user.id
		if @deal.save
			flash[:success] = "Successfully added a new deal"
			redirect_to program_deals_path
		else
			flash[:error] = "Could not add a new deal"
			redirect_to programs_path
		end
	end
	
	def index
		@title = "Deals"
		@zone = "Application"
  end
	
	def edit
		@zone = "Application"
		@deal = Deal.find(params[:id])
		@customer = Account.find(@deal.customer_id)
		@title = @deal.customer.name
  end
	
  def show
		@zone = "Application"
		@deal = Deal.find(params[:id])
		@title = @deal.name
  end
	
	def destroy
		Deal.find(params[:id]).destroy
    flash[:success] = "Deal deleted."
    redirect_to program_deals_path
	end
	
	def update
		@deal = @program.deals.find(params[:id])
		if params[:commit] == "Update"
			if @deal.update_attributes(params[:deal])
				flash[:success] = "Deal updated."
				redirect_to program_deals_path
			else
				redirect_to program_deals_path
			end
		elsif params[:commit] == "Cancel"
			redirect_to program_deals_path
		end
	end
	
	def find_program
		@program = Program.find(params[:program_id])
	end
	
	def find_deals
		@deals = @program.deals
	end
	
	def find_customers
		#@customers = Account.find(:all, :conditions => {:service => 'customer', :id => current_partners})
		@customers = Account.find(:all, :conditions => ["id NOT IN (SELECT customer_id FROM deals WHERE program_id = ?)
				AND service = ? AND id IN (?)", @program.id, "customer", current_partners])
	end
	
	def find_plan
		@plan = @program.plan
	end
	
end

app/views/deals/_deal.erb

  <tr>
    <td><%= deal != nil ? deal.program.seller.name : nil %></td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= deal != nil ? deal.id : nil %></td>
    <td><%= deal.customer != nil ? deal.customer.name : nil %></td>
    <td></td>
    <td></td>
    <%= render deal.deal_products %>
  </tr>

app/views/deals/_new.html.erb
<%= form_for [@program, deal] do |f| %>
  <div class="field">
    <%#TODO: Add class tags to these for proper sizing%>
    <td><%= f.collection_select(:customer_id, @customers, :id, :name) %></td>
    <td><%= f.collection_select(:status, Deal::DEAL_STATUS, :to_s, :humanize) %></td>
    <td><%= f.text_field :offered_to %></td>
    <td><%= f.text_field :offered_on %></td>
    <td><%= f.text_field :accepted_by %></td>
    <td><%= f.text_field :accepted_on %></td>
  
  
  </div>
  <div class="actions">
    <td>
      <%= f.submit "Submit" %>
    </td>
  </div>
  <td />
<% end %>
  


app/views/deals/_program.html.erb
<table>
  <tr>
    
    <th>Code</th>
    <th>Name</th>
    <th>Description</th>
    <th>Account</th>
    <th>Start</th>
    <th>End</th>
    <th></th>
    <th>Category</th>
    <th>Budgeted<br />Rate</th>
    <th>Budgeted<br />Volume</th>
    <th>Budgeted<br />Cost</th>
    
    
  </tr>
  
    
      <tr>  
        <td><%= p.code %></td>
        <td><%= p.name %> </td>
        <td><%= p.descr %></td>
        <td><%= p.account.name %></td>
        <td><%= p.start_date %></td>
        <td><%= p.end_date %></td>
        <td></td>
        <td><%= p.category.code %></td>        
        <td class="number_field"><%= p.budget_rate && number_to_currency(p.budget_rate) %></td>
        <td class="number_field"><%= p.budget_vol && float_zero(p.budget_vol) %></td>
        <td class="number_field"><%= currency_zero(p.budget_cost) %></td>        
        
      </tr>
    
  
</table>

app/views/deals/edit.html.erb
<h2>Edit Deal</h2>

<%= form_for [@program, @deal] do |f| %>
  <div class="field">
    <%= f.label :name, "Customer", :class => "field_label" %>
    <%= f.collection_select(:customer_id, @customers, :id, :name) %><br />
  </div>
  <div class="field">
    <%= f.label :name, "Status", :class => "field_label" %>
    <%= f.collection_select(:status, Deal::DEAL_STATUS, :to_s, :humanize) %><br />
  </div> 
  <div class="field">
    <%= f.label :name, "Offered To", :class => "field_label" %>
    <%= f.text_field :offered_to %><br />
  </div> 
  <div class="field">
    <%= f.label :name, "Offer Date", :class => "field_label" %>
    <%= f.text_field :offered_on %><br />
  </div> 
  <div class="field">
    <%= f.label :name, "Accepted By", :class => "field_label" %>
    <%= f.text_field :accepted_by %><br />
  </div> 
  <div class="field"> 
    <%= f.label :name, "Date Accepted", :class => "field_label" %>
    <%= f.text_field :accepted_on %><br /> 
  </div>
  
  <div class="actions">
    <%= submit_tag "Update" %>
    <%= submit_tag "Cancel" %>
  </div>

<% end %>

app/views/deals/index.html.erb
<p class="trail"><%= link_to "Plans (#{@plan.code})", plans_path %> > <%= link_to "Programs (#{@program.code})", plan_programs_path(@plan.id) %> > Deals</p>


<table id="deals-index" class="dataTable">
  <thead>
    
    <tr>

      <th>Customer</th>
      <th>Status</th>
      <th>Offered To</th>
      <th>Offered On</th>
      <th>Accepted By</th>
      <th>Accepted On</th>
      <th>Offered Expense</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <% @deals.each do |deal| %>
    <tr>

      <td><%= link_to deal.customer.name, deal_deal_products_path(deal) %></td>
      <td><%= deal.status %></td>
      <td><%= deal.offered_to %></td>
      <td><%= deal.offered_on %></td>
      <td><%= deal.accepted_by %></td>
      <td><%= deal.accepted_on %></td>
      <td><%= deal.plan_expense %></td>
      <td><%= link_to "Edit", edit_program_deal_path(@program, deal)%></td>
      <td><%= link_to "Delete", program_deal_path(@program.id, deal.id), :method => :delete, :confirm => "Please confirm deletion:",
                      :title => "Delete Deal for #{deal.customer.name}" %></td>
    </tr>
  <% end %>     
</table>

<%= render :partial => 'new', :locals => { :deal => @program.deals.new } %>

<script>
  $(document).ready(function() {
    $('#deals-index').dataTable({
      "bJQueryUI": true
    });
  } );

</script>

app/views/deals/new.html.erb
<p>Add New Deal</p>

<table>
	<tr>
		<th>Code</th>
		<th>Name</th>
		<th>Description</th>
		<th>Start</th>
		<th>End</th>
		<th>Rate</th>
		<th>Volume</th>
	</tr>
	<tr>
		<%= form_for([@program, @deal]) do |f| %>
			<div class="field">
				
				<td><%= f.text_field :code %></td>
				
				<td><%= f.text_field :name %></td>
				
				<td><%= f.text_field :descr %></td>
				
				<td><%= f.text_field :start_date %></td>
				
				<td><%= f.text_field :end_date %>
				
				<td><%= f.number_field :deal_rate, :step => 0.01 %></td>
				
				<td><%= f.number_field :deal_vol %></td>
				
				</td>
			</div>
			<div class="actions">
				<td>
					<%= f.submit "Submit" %>
				</td>
			</div>
			<td />
		<% end %>
	<tr/>
</table>

app/views/deals/show.html.erb
<h1>Deals#show</h1>
<p>Find me in app/views/deals/show.html.erb</p>