config/routes.rb
SimplePlan::Application.routes.draw do  

  devise_for :users, :controllers => { :registrations => "registrations" }
		
  match 'programs/grid_data', :to => 'programs#grid_data'
	match 'programs/list', :to => 'programs#list'
	match 'programs/filter', :to => 'programs#filter'
	
	resources :activities
	resources	:accounts	
	resources :services
	resources :profiles
	resources :partnerships
	resources	:categories
	resources	:products
  resources :program_categories
  resources :program_products
  resources :program_activities
	resources :imports
	resources :worksheets
	
	resources :budgets do
		resources :plans
	end
	
	resources	:plans do
		resources	:programs do
			member do
				get 'copy'
			end
		end
	end
	
	resources	:programs do
		member do
			get 'copy'
		end
		resources	:deals	
	end
	
	resources :deals do
		resources :deal_products
	end
		
	resources :deal_products do
		resources :deal_activities
	end
	
	namespace :user do
		root :to => 'users#dashboard'
	end
	
	match 'users' => 'users#dashboard', :as => 'user_root'

	match '/help',			:to => 'pages#help'
	match '/about',			:to => 'pages#about'
	match '/contact',		:to => 'pages#contact'
	match '/user',			:to => 'users#show'
	match '/users',			:to => 'users#index'
	
	root :to => 'pages#home'

  
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to 	:account
	belongs_to 	:category_product
	belongs_to	:program_product
	has_many		:deals
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
include ApplicationHelper
require 'csv'
before_filter	:authorize_products
before_filter { |c| c.set_zone "Application" }

  def index
		@title = "Products"
		@product = Product.new
	end
	
	def show
		@product = Product.find(params[:id])
		@title = @product.name
	end

  def new
		redirect_to products_path
  end
	
	def edit
		@product = Product.find(params[:id])
		@title = @product.name
	end
	
	def update
		@product = Product.find(params[:id])
		if @product.update_attributes(params[:product])
			flash[:success] = "Product updated."
			redirect_to products_path
		else
			redirect_to products_path
		end
	end
	
	def create
		@product = Product.new(params[:product])
		@product.account_id = current_account.id
		if @product.save
			flash[:success] = "Successfully added a new product"
			redirect_to products_path
		else
			redirect_to products_path
		end
	end
	
	def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Product deleted."
    redirect_to products_path
  end
	
	def authorize_products
		@products = Product.find(:all, :conditions => [ "account_id IN (?) OR account_id = (?)", current_partners, current_account])
	end
	
end

app/views/products/_new.html.erb
<tr>
  <%= form_for(@product) do |f| %>
    <div class="field">
      <td>
        <%= f.text_field :code %>
      </td>
      <td>
        <%= f.text_field :name %>
      </td>
    </div>
    <div class="actions">
      <td>
        <%= f.submit "Submit" %>
      </td>
    </div>
      <td></td>
      <td></td>
      <td></td>
  <% end %>
<tr/>

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<%= form_for(@product) do |f| %>
	<div class="field">
		<%= f.label :name, "Code", :class => "field_label" %><br />
		<%= f.text_field :code %><br/>
	</div>
	<div class="field">
		<%= f.label :name, "Name", :class => "field_label" %><br />
		<%= f.text_field :name %><br/>
	</div>	
	<div class="actions">
		<%= f.submit "Update" %>
	</div>
<% end %>

app/views/products/import.html.erb
<%= form_for :dump, :url=>{
	:controller=>"products",
	:action=>"csv_import"},
        :html => { :multipart => true } do |f| %>
        CSV:
        <%= f.file_field :file %>
        <%= submit_tag 'Import' %>
<% end %>

app/views/products/index.html.erb
<h2>Products</h2>

  <table>
    <tr>
      <td>Code</td>
      <td>Name</td>
      <td>Description</td>
      <td>Account</td>
      <td></td>
      <td></td>
    </tr>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.code, product %></td>
          <% if !product.name %>
            <td></td>
          <% else %>
            <td><%= product.name %></td>
          <% end %>

          <% if !product.descr %>
            <td />
          <% else %>
            <td><%= product.descr %></td>
          <% end %>

        <td><%= product.account.name %></td>

        <td><%= link_to "Edit", edit_product_path(product) %></td>
        <td><%= link_to "Delete", product, :method => :delete, :confirm => "Please confirm deletion:",
          :title => "Delete #{product.name}" %></td>
        
        
     </tr>
    <% end %>
    <%= render 'new' %>
  </table>
  <br />
  <%= link_to "Import Data", new_import_path(:model => 'Product') %>

app/views/products/show.html.erb
<%= render :partial => "shared/show", :locals => { :object => @product } %>
	
	<div>
		<p><%= link_to "Edit", edit_product_path(@product) %></p>
		<p><%= link_to "Delete", @product, :method => :delete, :confirm => "Please confirm deletion:",
																						:title => "Delete #{@product.name}" %></P>
		<p><%= link_to "Back", :back %></p>
	</div>																		